version: '3.4'

services:

  # Apps

  api: &api
    build: 
      args: &dotnet-args
        NUGET_SOURCE: ${NUGET_SOURCE}
        NUGET_USER_NAME: ${NUGET_USER_NAME}
        NUGET_PASSWORD: ${PERSONAL_ACCESS_TOKEN}

        DOTNET_ASPNET_IMAGE: mcr.microsoft.com/dotnet/aspnet:8.0
        DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:8.0
    ports:
      - 5000:8080
    environment: &dotnet-env
      ASPNETCORE_ENVIRONMENT: Development
      
      ConnectionStrings__DefaultConnection: Server=reminders-mssql;Database=Reminders;User ID=sa;Password=h9pJwUUV0y;MultipleActiveResultSets=True;Application Name=Reminders;Persist Security Info=True;Trust Server Certificate=True;
    volumes: &dotnet-volumes
      - user_secrets:/root/.microsoft/usersecrets:ro
      - https_certificates:/root/.aspnet/https:ro
      - data_protection_keys:/root/.aspnet/DataProtection-Keys

  api-2: 
    <<: *api
    ports:
      - 5001:8080

  mvc:
    build: 
      args: *dotnet-args
    environment: *dotnet-env
    ports:
      - 5050:8080
    volumes: *dotnet-volumes

  # Database

  mssql:
    environment:
      SA_PASSWORD: "h9pJwUUV0y"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
  
  postgres:
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: h9pJwUUV0y 
    ports:
      - 5432:5432

  # Load Balancer

  nginx: 
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"

volumes:

  user_secrets:
    driver: local
    driver_opts:
      type: none
      device: $HOME/.microsoft/usersecrets
      o: bind

  https_certificates:
    driver: local
    driver_opts:
      type: none
      device: $HOME/.aspnet/https
      o: bind
  
  data_protection_keys:
    driver: local
    driver_opts:
      type: none
      device: $HOME/.aspnet/DataProtection-Keys
      o: bind