version: '3'

networks:
  reminders-network:
    driver: bridge

services:
  reminders-aspnetapi-database:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: reminders-database
    environment:
      SA_PASSWORD: '123Aa321'
      ACCEPT_EULA: 'Y'
    ports:
      - '18000:1433'
    networks:
      - reminders-network
