version: '3'

networks: 
    reminders-network:
        driver: bridge

services:
    reminders-database:
        image: reminders-database-image:latest
        container_name: reminders-database
        build: 
            context: ./infrastructure/mssql
            dockerfile: ./src/Dockerfile
        networks: 
            - reminders-network
    reminders-migrations:
        image: reminders-migrations-image:latest
        container_name: reminders-migrations
        build: 
            context: .
            dockerfile: ./src/Dockerfile.migrations
            args: 
                DOTNET_PROJECT_PATH: ./Reminders.Infrastructure.Data
                DOCKER_DATABASE_CONTAINER: reminders-database:1433
                WAIT_FOR_SCRIPT: ./infrastructure/wait-for.sh
                WAIT_FOR_TIMEOUT: 4000
        networks: 
            - reminders-network
        depends_on: 
            - reminders-database
    reminders-aspnetmvc:
        image: reminders-aspnetmvc-image:latest
        container_name: reminders-aspnetmvc
        build: 
            context: .
            dockerfile: ./src/Dockerfile
            args: 
                DOTNET_PROJECT_PATH: ./Reminders.Mvc
        networks: 
            - reminders-network
        depends_on: 
            - reminders-migrations
    reminders-aspnetapi:
        image: reminders-aspnetapi-image:latest
        container_name: reminders-aspnetapi
        build: 
            context: .
            dockerfile: ./src/Dockerfile
            args: 
                DOTNET_PROJECT_PATH: ./Reminders.Api
        networks: 
            - reminders-network
        depends_on: 
            - reminders-migrations
