# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  reminders-mvc:
    image: reminders-mvc
    build:
      context: .
      dockerfile: src/Web/Reminders.Mvc/Dockerfile
    ports:
      - 5000:5000
  reminders-api:
    image: reminders-api
    build:
      context: .
      dockerfile: src/Web/Reminders.Api/Dockerfile
    ports:
      - 5000:5000
