version: '3'

networks: 
    reminders-network:
        driver: bridge

services:
    reminders-database:
        image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
        container_name: reminders-database
        networks: 
            - reminders-network
    reminders-build:
        image: reminders-build-image:latest
        container_name: reminders-build
        build: 
            context: .
            dockerfile: dockerfile
        command: sh -c '/app/wait-for.sh reminders-database:1433 -t 2000 -- dotnet ef database update --project /app/src/Reminders.Infrastructure.Data/'
        depends_on: 
            - reminders-database
        networks: 
            - reminders-network
    reminders-mvc:
        image: reminders-mvc-image:latest
        container_name: reminders-mvc
        build: 
            context: .
            dockerfile: mvc.dockerfile
        command: sh -c '/app/wait-for.sh reminders-database:1433 -t 2000 -- dotnet /app/Reminders.Mvc.dll'
        networks: 
            - reminders-network
        depends_on: 
            - reminders-build
    reminders-api:
        image: reminders-api-image:latest
        container_name: reminders-api
        build: 
            context: .
            dockerfile: api.dockerfile
        command: sh -c '/app/wait-for.sh reminders-database:1433 -t 2000 -- dotnet /app/Reminders.Api.dll'
        networks: 
            - reminders-network
        depends_on: 
            - reminders-mvc