version: "3"

networks:
  reminders-network:
    driver: bridge

services:
  reminders-database:
    image: reminders-database-image:latest
    container_name: reminders-database
    ports:
      - "17000:1433"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - reminders-network
