version: '3.4'

services:
  reminders-mvc:
    image: reminders-mvc
    build:
      context: .
      dockerfile: src/Web/Reminders.Mvc/Dockerfile
    ports:
      - 5000:5000
    profiles:
      - reminders-mvc

  reminders-api:
    image: reminders-api
    build:
      context: .
      dockerfile: src/Web/Reminders.Api/Dockerfile
    ports:
      - 5000:5000
    profiles:
      - reminders-api

  reminders-db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    profiles:
      - reminders-mvc
      - reminders-api
