version: '3'

networks: 
    reminders-network:
        driver: bridge

services:
    reminders-database:
        image: reminders-database-image:lastest
        container_name: reminders-database
        build: 
            context: ./infrastructure/mssql
            dockerfile: Dockerfile
        networks: 
            - reminders-network
    reminders-migrations:
        image: reminders-migrations-image:latest
        container_name: reminders-migrations
        build: 
            context: .
            dockerfile: migrations.Dockerfile
            args: 
                DOTNET_PROJECT_PATH: ./src/Reminders.Infrastructure.Data
                DOCKER_DATABASE_CONTAINER: reminders-database:1433
                WAIT_FOR_SCRIPT: ./infrastructure/wait-for.sh
                WAIT_FOR_TIMEOUT: 4000
        networks: 
            - reminders-network
        depends_on: 
            - reminders-database
    reminders-aspnetmvc:
        image: reminders-aspnetmvc-image:latest
        container_name: reminders-aspnetmvc
        build: 
            context: .
            dockerfile: Dockerfile
            args: 
                DOTNET_PROJECT_PATH: ./src/Reminders.Mvc
        environment: 
            ENV_DOTNET_ENTRYPOINT: Reminders.Mvc.dll
        networks: 
            - reminders-network
        depends_on: 
            - reminders-migrations
    reminders-aspnetapi:
        image: reminders-aspnetapi-image:latest
        container_name: reminders-aspnetapi
        build: 
            context: .
            dockerfile: Dockerfile
            args: 
                DOTNET_PROJECT_PATH: ./src/Reminders.Api
        environment: 
            ENV_DOTNET_ENTRYPOINT: Reminders.Api.dll
        networks: 
            - reminders-network
        depends_on: 
            - reminders-migrations
