version: '3.4'

services:

  # Apps

  dotnet-api:
    image: reminders-dotnet-api
    container_name: reminders-dotnet-api
    build: 
      context: src/server/api/dotnet/Reminders.Api
    depends_on:
      - postgres
    profiles: 
      - all
      - api
    deploy: &shared-deploy
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  go-api: 
    image: reminders-go-api
    container_name: reminders-go-api
    build: 
      context: src/server/api/go/reminders-api
    depends_on:
      - postgres
    profiles: 
      - all
      - api
    deploy: *shared-deploy

  mvc:
    image: reminders-mvc
    container_name: reminders-mvc
    build:
      context: .
      dockerfile: src/app/dotnet/Reminders.Mvc/Dockerfile
    depends_on:
      - nginx
    profiles:
      - all
      - mvc
    deploy: *shared-deploy

  react:
    image: reminders-react
    container_name: reminders-react
    build:
      context: .
      dockerfile: src/app/reactjs/reminders-app/Dockerfile
    depends_on:
      - nginx
    profiles:
      - all
    deploy: *shared-deploy

  # Database

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: reminders-mssql
    profiles:
      - all-old
      # - api
      # - mvc

  postgres:
    image: postgres
    container_name: reminders-postgres
    profiles:
      - all
      - api
      - mvc
    deploy: *shared-deploy

  # Load Balancer

  nginx: 
    image: nginx:latest
    container_name: reminders-nginx
    depends_on:
      - dotnet-api
      - go-api
    profiles:
      - all
      - api
    deploy: *shared-deploy

networks:
  default:
    name: 'reminders-network'
    driver: bridge