version: '3.4'


services:
  mvc:
    image: reminders-mvc
    container_name: reminders-mvc
    build:
      context: .
      dockerfile: src/Web/Reminders.Mvc/Dockerfile
    profiles:
      - mvc

  api:
    image: reminders-api
    container_name: reminders-api
    build:
      context: .
      dockerfile: src/Web/Reminders.Api/Dockerfile
    profiles:
      - api

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: reminders-database
    profiles:
      - mvc
      - api

networks:
  default:
    name: 'reminders-network'
    driver: bridge