version: '3.4'

services:
  mvc:
    build: 
      args:
        DOTNET_VERSION: 8.0-alpine
    ports:
      - 5000:80
    environment:
      ConnectionStrings__DefaultConnection: Server=reminders-database;Database=Reminders;User ID=sa;Password=h9pJwUUV0y;MultipleActiveResultSets=True;Application Name=Reminders;

  api:
    build: 
      args:
        DOTNET_VERSION: 8.0-alpine
    environment:
      ConnectionStrings__DefaultConnection: Server=reminders-database;Database=Reminders;User ID=sa;Password=h9pJwUUV0y;MultipleActiveResultSets=True;Application Name=Reminders;
    ports:
      - 5001:80

  db:
    environment:
      SA_PASSWORD: "h9pJwUUV0y"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'