version: '3'

services: 
    reminders-database:
        environment:
            - SA_PASSWORD=123Aa321
            - ACCEPT_EULA=Y
        ports:
            - "17000:1433"
    reminders-build:
        env_file: 
            - .env
    reminders-mvc:
        env_file: 
            - .env
        ports:
            - "17001:80"
    reminders-api:
        env_file: 
            - .env
        ports:
            - "17002:80"