version: '3.4'

services:

  # Apps

  api: &api
    image: reminders-api
    container_name: reminders-api
    build: 
      context: .
      dockerfile: src/server/api/dotnet/Reminders.Api/Dockerfile
    depends_on:
      - postgres
      - ganache
    profiles: 
      - all
      - api
    deploy: &shared-deploy
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api-2:
    <<: *api
    container_name: reminders-api-2

  mvc:
    image: reminders-mvc
    container_name: reminders-mvc
    build:
      context: .
      dockerfile: src/app/dotnet/Reminders.Mvc/Dockerfile
    depends_on:
      - nginx
    profiles:
      - all
      - mvc
    deploy: *shared-deploy

  react:
    image: reminders-react
    container_name: reminders-react
    build:
      context: .
      dockerfile: src/app/reactjs/reminders-app/Dockerfile
    depends_on:
      - nginx
    profiles:
      - all
    deploy: *shared-deploy

  # Database

  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: reminders-mssql
    profiles:
      - all-old
      # - api
      # - mvc

  postgres:
    image: postgres
    container_name: reminders-postgres
    profiles:
      - all
      - api
      - mvc
    deploy: *shared-deploy

  # Load Balancer

  nginx: 
    image: nginx:latest
    container_name: reminders-nginx
    depends_on:
      - api
      - api-2
    profiles:
      - all
      - api
    deploy: *shared-deploy

  # Blockchain
  ganache:
    image: trufflesuite/ganache
    container_name: reminders-blockchain
    ports:
      - "8545:8545"
    command:
      - --accounts=10
      - --defaultBalanceEther=1000
      - --mnemonic="candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
    restart: unless-stopped

  # blockscout:
  #   image: blockscout/blockscout:latest
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - ETHEREUM_JSONRPC_VARIANT=ganache
  #     - ETHEREUM_JSONRPC_HTTP_URL=http://ganache:8545
  #     - ETHEREUM_JSONRPC_WS_URL=ws://ganache:8545
  #     - DATABASE_URL=postgresql://postgres:password@db:5432/blockscout
  #     - SECRET_KEY_BASE=56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN
  #   depends_on:
  #     - ganache
  #     - db

  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=blockscout
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: 'reminders-network'
    driver: bridge