version: "3"

networks:
  reminders-network:
    driver: bridge

services:
  reminders-aspnetmvc-database:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    container_name: reminders-aspnetmvc-database
    environment:
      SA_PASSWORD: 123Aa321
      ACCEPT_EULA: Y
    ports:
      - "17000:1433"
    networks:
      - reminders-network
  reminders-aspnetmvc:
    image: reminders-aspnetmvc-image:latest
    container_name: reminders-aspnetmvc
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings:DefaultConnection: Server=reminders-aspnetmvc-database;Database=Reminders;User=sa;Password=123Aa321;TrustServerCertificate=True;MultipleActiveResultSets=True;
    ports:
      - "17001:80"
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - reminders-network
    depends_on:
      - reminders-aspnetmvc-database
