@url = http://localhost:5001

@id = 

###

GET {{url}}/api/Reminders/
Accept: application/json

###

POST {{url}}/api/Reminders/
Accept: application/json
Content-Type: application/json

{
  "title": "string",
  "description": "string",
  "limitDate": "2024-12-20T18:44:37.637Z",
  "isDone": true
}

###

GET {{url}}/api/Reminders/{{id}}
Accept: application/json

###

PUT {{url}}/api/Reminders/{{id}}
Accept: application/json
Content-Type: application/json

{
  "id": "{{id}}",
  "title": "string edited",
  "description": "string edited",
  "limitDate": "2024-12-20T18:44:37.637Z",
  "isDone": true
}

###

DELETE {{url}}/api/Reminders/{{id}}
Accept: application/json