<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>11.0</LangVersion>
    <Version>8.0.0</Version>
    <PackageDescription>Reminders Api Test</PackageDescription>
    <RepositoryUrl>https://github.com/kauereinbold/Reminders</RepositoryUrl>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.31" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\server\api\dotnet\Reminders.Api\Reminders.Api.csproj" />
  </ItemGroup>
  
</Project>