version: '3'

networks:
  kauereinbold-reminders-network:
    driver: bridge

services:
  kauereinbold-reminders-database:
    image: kauereinbold/reminders-database-image:latest
    container_name: kauereinbold-reminders-database
    ports:
      - '5033:1433'
    environment:
      - SA_PASSWORD: 123Aa321
      - REMINDERS_PASSWORD: D6jcdaWLsBh64adr
      - ACCEPT_EULA: Y
    networks:
      - kauereinbold-reminders-network
  kauereinbold-reminders-migrations:
    image: kauereinbold/reminders-migrations-image:latest
    container_name: kauereinbold-reminders-migrations
    networks:
      - kauereinbold-reminders-network
    depends_on:
      - kauereinbold-reminders-database
  kauereinbold-reminders-aspnetapi:
    image: kauereinbold/reminders-aspnetapi-image:latest
    container_name: kauereinbold-reminders-aspnetapi
    ports:
      - '5002:80'
    environment:
      ENV_DOTNET_ENTRYPOINT: Reminders.Api.dll
      ConnectionStrings:DefaultConnection: ConnectionStrings:DefaultConnection=Server=reminders-database;Database=Reminders;User=reminders;Password=D6jcdaWLsBh64adr;TrustServerCertificate=True;MultipleActiveResultSets=True;
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - kauereinbold-reminders-network
    depends_on:
      - kauereinbold-reminders-migrations
  kauereinbold-reminders-aspnetmvc:
    image: kauereinbold/reminders-aspnetmvc-image:latest
    container_name: kauereinbold-reminders-aspnetmvc
    ports:
      - '5000:80'
    environment:
      ENV_DOTNET_ENTRYPOINT: Reminders.Mvc.dll
    networks:
      - kauereinbold-reminders-network
    depends_on:
      - kauereinbold-reminders-aspnetapi
