version: '3.4'

name: stress-testing

services:

  # Stress Test

  influxdb:
    image: influxdb:1.8
    container_name: reminders-influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  # http://localhost:3000/d/k6/k6-load-testing-results
  grafana:
    image: grafana/grafana:8.5.21
    container_name: reminders-grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_BASIC_ENABLED: false
      GF_SERVER_SERVE_FROM_SUB_PATH: true
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6: &k6
    image: grafana/k6:latest
    container_name: reminders-k6
    ports:
      - "6565:6565"
    environment:
      K6_OUT: influxdb=http://localhost:8086/k6
      BASE_URL: http://localhost:9999
    profiles:
      - k6
    volumes:
      - ./scripts:/scripts

  post:
    <<: *k6
    container_name: reminders-k6-post
    command: run /scripts/k6.post.js
    network_mode: host

  get:
    <<: *k6
    container_name: reminders-k6-get
    command: run /scripts/k6.get.js
    network_mode: host

  delete:
    <<: *k6
    container_name: reminders-k6-delete
    command: run /scripts/k6.delete.js
    network_mode: host