name: docker - build - pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Reminders.Mvc - Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: src/app/dotnet/Reminders.Mvc/Dockerfile
          build-args: |
            DOTNET_ASPNET_IMAGE=mcr.microsoft.com/dotnet/aspnet:8.0
            DOTNET_SDK_IMAGE=mcr.microsoft.com/dotnet/sdk:8.0
          push: false

      - name: Reminders.Api - Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: src/server/api/dotnet/Reminders.Api/Dockerfile
          build-args: |
            DOTNET_ASPNET_IMAGE=mcr.microsoft.com/dotnet/aspnet:8.0
            DOTNET_SDK_IMAGE=mcr.microsoft.com/dotnet/sdk:8.0
          push: false
