name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Push Reminders Database to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@2.12
        env:
          SA_PASSWORD: 123Aa321
          ACCEPT_EULA: Y
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/reminders-database-image
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: .
          tag_names: true
