name: Docker Image CI

on: 
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push Reminders Database to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      env: 
        SA_PASSWORD: 123Aa321
        ACCEPT_EULA: Y
        ASPNETCORE_ENVIRONMENT: Docker
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/reminders-database-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./infrastructure/mssql
        tag_names: true  
    - name: Push Reminders Migrations to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      env: 
        ASPNETCORE_ENVIRONMENT: Docker
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/reminders-migrations-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: migrations.Dockerfile
        buildargs: DOTNET_PROJECT_PATH=./src/Reminders.Infrastructure.Data,DOCKER_DATABASE_CONTAINER=reminders-database:1433,WAIT_FOR_SCRIPT=./infrastructure/wait-for.sh,WAIT_FOR_TIMEOUT=4000
        tag_names: true  
    - name: Push Reminders Mvc to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      env: 
        ENV_DOTNET_ENTRYPOINT: Reminders.Mvc.dll
        ASPNETCORE_ENVIRONMENT: Docker
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/reminders-aspnetmvc-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: DOTNET_PROJECT_PATH=./src/Reminders.Mvc
        tag_names: true
        source-url: https://nuget.pkg.github.com/KaueReinbold/index.json
    - name: Push Reminders Api to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@2.12
      env: 
        ENV_DOTNET_ENTRYPOINT: Reminders.Api.dll
        ASPNETCORE_ENVIRONMENT: Docker
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/reminders-aspnetapi-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: DOTNET_PROJECT_PATH=./src/Reminders.Api
        tag_names: true  
        source-url: https://nuget.pkg.github.com/KaueReinbold/index.json