name: .NET Core

on: 
  pull_request:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release src/Reminders.Application.Test
    - name: Publish Mvc
      run: dotnet publish -c Release src/Reminders.Mvc
    - name: Upload Artifact Mvc
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Reminders-Mvc 
        path: src/Reminders.Mvc/bin/Release/netcoreapp3.1/publish
    - name: Publish Api
      run: dotnet publish -c Release src/Reminders.Api
    - name: Upload artifact Api
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Reminders-Api
        path: src/Reminders.Api/bin/Release/netcoreapp3.1/publish
