name: dotnet - build - code coverage

on:
  push:
    branches:
      - main
    paths:
      - './src/**/dotnet/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"
          source-url: https://nuget.pkg.github.com/KaueReinbold/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore
        run: dotnet restore ./src

      - name: Build
        run: dotnet build -c Release ./src

      - name: Test
        run: dotnet test -c Release src/test/server/dotnet/Reminders.Application.Test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov /p:Exclude=\"[Reminders.Infrastructure.CrossCutting]*,[Reminders.Infrastructure.Data.EntityFramework]*,[Reminders.Infrastructure.Data.EntityFramework.SqlServer]*,[Reminders.Infrastructure.Data.EntityFramework.Postgres]*\" /p:ExcludeByFile=\"**/*.Designer.cs,**/*Entity.cs\"

      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: src/test/server/dotnet/Reminders.Application.Test/TestResults/coverage.info
